---
- name: Copy Magic Mirror config.js
  ansible.builtin.template:
    src: 'files/config.js.j2'
    dest: "{{ mm_root }}/config/config.js"

- name: Check Magic Mirror config.js file
  command: npm run config:check
  args:
    chdir: "{{ mm_root }}/config"
  notify:
    - Restart Magic Mirror