---
- name: Download and run MagicMirror installation script
  shell: |
    yes | curl -sL https://raw.githubusercontent.com/sdetweil/MagicMirror_scripts/master/raspberry.sh | bash
  args:
    chdir: /home/pi