---
- name: "Download Modules"
  ansible.builtin.git:
    repo: "{{ MM.github }}"
    dest: "{{ mm_root }}/modules/{{ item.name }}"
    clone: yes
    force: yes
    update: yes
  loop: "{{ mm_modules }}"

- name: "NPM Install Modules"
  ansible.builtin.npm:
    path: "{{ mm_root }}/modules/{{ item.name }}"
  ignore_errors: yes
  loop: "{{ mm_modules }}"

# - name: Magic Mirror Config.js
#   copy:
#     src: './files/config.js.j2'
#     dest: "{{ mm_root }}/config/config.js"

# - name: check config.js file
#   command:
#     chdir: "{{ mm_root }}/config"
#     cmd: npm run config:check
#   notify:
#     - restart MM

# - name: restart MM
#   shell: "cd {{ mm_root }} && pm2 restart MagicMirror"
#   ignore_errors: true
#
#
#
#
#
# - name: Install and configure Magic Mirror modules
#   block:
#     - name: Check if default module directory exists
#       stat:
#         path: "{{ mm_root }}/modules/default/{{ item.name }}"
#       register: default_module_dir
#       loop: "{{ mm_modules }}"
#       loop_control:
#         label: "{{ item.name }}"

#     - name: Check if custom module directory exists
#       stat:
#         path: "{{ mm_root }}/modules/{{ item.name }}"
#       register: custom_module_dir
#       loop: "{{ mm_modules }}"
#       loop_control:
#         label: "{{ item.name }}"

#     - name: Download Module with GitHub repo
#       ansible.builtin.git:
#         repo: "{{ item.github }}"
#         dest: "{{ mm_root }}/modules/{{ item.name }}"
#         clone: yes
#         force: yes
#         update: yes
#       loop: "{{ mm_modules }}"
#       loop_control:
#         label: "{{ item.name }}"
#       when: item.github is defined and (item not in default_module_dir.results | map(attribute='item.name') | list) and (item not in custom_module_dir.results | map(attribute='item.name') | list)

#     - name: NPM Install Module
#       ansible.builtin.npm:
#         path: "{{ mm_root }}/modules/{{ item.name }}"
#       loop: "{{ mm_modules }}"
#       loop_control:
#         label: "{{ item.name }}"
#       when: item.github is not defined and (item not in default_module_dir.results | map(attribute='item.name') | list) and (item not in custom_module_dir.results | map(attribute='item.name') | list)

#   when: mm_modules | length > 0

#
#
#

# - name: Check if custom CSS file exists
#   stat:
#     path: "files/{{ hosts }}.custom.css"
#   register: custom_css_file

# - name: Copy custom.css if exists
#   ansible.builtin.copy:
#     src: "files/{{ hosts }}.custom.css"
#     dest: "{{ mm_root }}/css/custom.css"
#   when: custom_css_file.stat.exists

# - name: Copy Magic Mirror config.js
#   ansible.builtin.template:
#     src: 'files/config.js.j2'
#     dest: "{{ mm_root }}/config/config.js"

# - name: Check Magic Mirror config.js file
#   command: npm run config:check
#   args:
#     chdir: "{{ mm_root }}/config"
#   notify:
#     - Restart Magic Mirror