---
- name: Turn off screen saver
  shell: |
    curl -sL https://raw.githubusercontent.com/sdetweil/MagicMirror_scripts/master/screensaveroff.sh | bash
  args:
    chdir: /home/pi

- name: Turn off screen saver
  become: true
  apt:
    name:
      - lxplug-ptbatt
    state: absent
    autoclean: true
    autoremove: true

- name: Download and run MagicMirror installation script
  shell: |
    yes | curl -sL https://raw.githubusercontent.com/sdetweil/MagicMirror_scripts/master/raspberry.sh | bash
  args:
    chdir: /home/pi

- name: Add using pm2 to autostart MagicMirror at bootup
  shell: |
    curl -sL https://raw.githubusercontent.com/sdetweil/MagicMirror_scripts/master/fixuppm2.sh | bash
  args:
    chdir: /home/pi

- name: Start MagicMirror
  shell: |
    pm2 start MagicMirror
  args:
    chdir: "{{ mm_root }}"