---
- name: Configure Proxmox hosts
  hosts: "{{ hosts }}"
  become: yes
  become_user: root
  gather_facts: yes

  vars_prompt:
    - name: "{{ vm_id }}"
      prompt: Enter the VM ID to configure
      private: no

  tasks:
    - name: Configure QSV passthrough for hosts
      ansible.builtin.import_tasks:
        file: tasks/configure_qsv.yml
      tags: ["qsv"]

    - name: Configure VM settings
      ansible.builtin.import_tasks:
        file: tasks/configure_vm.yml
      tags: ["vm"]

  handlers:
    - name: update_grub
      command: update-grub
