---
- name: Install MagicMirror on Raspberry Pi
  hosts: "{{ hosts }}"
  become: yes
  gather_facts: no
  vars_files:
    - "{{ playbook_dir }}/files/{{hosts}}.yml"

  tasks:
     - name: Include prerequisites
      ansible.builtin.import_tasks:
        file: tasks/prerequisites.yml
      when: configure_prerequisites
      tags: ["prerequisites"]   

     - name: Install Magic Mirror
      ansible.builtin.import_tasks:
        file: tasks/install_mm.yml
      when: install_magicmirror
      tags: ["magicmirror"]   

     - name: Install Modules
      ansible.builtin.import_tasks:
        file: tasks/install_modules.yml
      when: install_modules
      tags: ["modules"]   



### For whatever reason PM2 commands need to be manuall ran for it to actually work
# pm2 startup systemd -u pi --hp /home/pi
# pm2 start /home/pi/MagicMirror/installers/mm.sh
# pm2 save