---
- name: Configure docker host
  hosts: "{{ hosts }}"
  become: yes
  become_user: ansible
  gather_facts: no
  vars_files:
    - "{{ playbook_dir }}/files/{{hosts}}.yml"

  tasks:
    - name: Install MagicMirror
      ansible.builtin.import_tasks:
        file: tasks/install_mm.yml
      when: install_magicmirror
      tags: ["magicmirror"]   

    - name: Install MagicMirror Modules
      ansible.builtin.import_tasks:
        file: tasks/install_modules.yml
      when: install_modules
      tags: ["modules"]   

    - name: Install custom CSS
      ansible.builtin.import_tasks:
        file: tasks/install_css.yml
      when: install_css
      tags: ["css"]      

    - name: Generate MagicMirror Configuration
      ansible.builtin.import_tasks:
        file: tasks/generate_config.yml
      when: generate_config
      tags: ["configure"]      

    - name: Upgrade MagicMirror
      ansible.builtin.import_tasks:
        file: tasks/upgrade_mm.yml
      when: upgrade_mm
      tags: ["upgrade"]   

  handlers:
    - name: Restart Magic Mirror
      shell: "cd {{ mm_root }} && pm2 restart MagicMirror"
      ignore_errors: true
