---
- name: Configure docker host
  hosts: "{{ hosts }}"
  become: yes
  become_user: "{{ becomeuser }}"
  gather_facts: yes

  tasks:
    - name: Install Docker
      ansible.builtin.import_tasks:
        file: tasks/install_docker.yml
      tags: ["docker"]   

    - name: Run container dockge
      ansible.builtin.import_tasks:
        file: tasks/run_dockge.yml
      tags: ["dockge"]      

  handlers:
    - name: Restart Docker
      ansible.builtin.service:
        name: docker
        state: restarted
