---
- name: Configure docker host
  hosts: "{{ hosts }}"
  become: yes
  become_user: root
  gather_facts: no

  tasks:
    - name: Install VM Tools
      ansible.builtin.import_tasks:
        file: tasks/install_vmtools.yml
      tags: ["vmtools"]   

    - name: Install Docker
      ansible.builtin.import_tasks:
        file: tasks/install_docker.yml
      tags: ["docker"]   

    - name: Run container dockge
      ansible.builtin.import_tasks:
        file: tasks/run_dockge.yml
      tags: ["dockge"]      

  handlers:
    - name: Reboot
      shell: sleep 2 && shutdown -r now "Ansible updates triggered"
      async: 1
      poll: 0
      ignore_errors: true
