---
install_rsat: true
mx_configuration: true
install_chocolately_packages: true
choco_installed_packages:
  - duck
  - filezilla
  #- powertoys    
  - vmrc
  - zoom
  ### Default Apps
  - cpu-z
  - everything
  - firefox
  - name: git
    choco_args:
    - '--params "/NoShellIntegration"'
  - googlechrome
  - googledrive
  - hwinfo
  - lghub
  - microsoft-windows-terminal
  - name: microsoft-office-deployment
    choco_args:
    - '--params="/64bit /Product:O365ProPlusRetail,VisioProRetail /Exclude:Groove,Lync,Publisher /RemoveMSI"'
  - obs-studio
  - revo-uninstaller
  - spotify
  - name: tightvnc
    choco_args: 
    - '--installArguments "ADDLOCAL=Viewer"'
  - vscode
  - vlc
  - winscp
  - wiztree
  - winrar

custom_taskbar: true
taskbar_pinned_icons:
  - '$env:PROGRAMDATA\Microsoft\Windows\Start Menu\Programs\Google Chrome.lnk'
  - '$env:USERPROFILE\Users\bkrathwohl\AppData\Roaming\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar\File Explorer.lnk'
  - '$env:PROGRAMDATA\Microsoft\Windows\Start Menu\Programs\Outlook.lnk'
  - '$env:SYSTEMROOT\Microsoft\Windows\Start Menu\Programs\Administrative Tools\Active Directory Users and Computers.lnk  - C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Everything.lnk'
  - '$env:PROGRAMDATA\Microsoft\Windows\Start Menu\Programs\Everything.lnk'
  - '$env:PROGRAMDATA\Microsoft\Windows\Start Menu\Programs\Administrative Tools\Group Policy Management.lnk'
  - '$env:PROGRAMDATA\Microsoft\Windows\Start Menu\Programs\Cygwin\Cygwin64 Terminal.lnk'
taskbar_registry_key:
  - mx-taskband.reg

# List of features: "Get-WindowsOptionalFeature -Online"
install_windows_features: false
windows_features:
  Microsoft-Hyper-V: true

# List of valid distributions that can be installed:
# wsl-alpine
# wsl-archlinux
# wsl-debiangnulinux
# wsl-fedoraremix
# wsl-kalilinux
# wsl-opensuse
# wsl-sles
# wsl-ubuntu-1604
# wsl-ubuntu-1804
# wsl-ubuntu-2004
install_wsl2: false
wsl2_distribution: wsl-ubuntu-2004

change_power_plan: false
# high_performance
# balanced
# power_saver
power_plan: "high_performance"
