---

# BATTLENET
# AMD ADRENALIN
# ASETEK RACEHUB

choco_additional_packages:
  - adobereader
  - aida64-extreme
  - autodesk-fusion360
  - brave
  - discord
  - epicgameslauncher
  - gpu-z
  - imgburn
  - lghub
  - msiafterburner
  - orcaslicer
  - rpi-imager
  - steam
  - tailscale
  ### Default Apps
  - cpu-z
  - everything
  - firefox
  - git
  - googlechrome
  - googledrive
  - hwinfo
  - lghub
  - microsoft-windows-terminal
  - name: microsoft-office-deployment
    choco_args: --params /64bit /Product:O365ProPlusRetail,VisioProRetail /Exclude:Groove,Lync,Publisher
  - obs-studio
  - revo-uninstaller
  - spotify
  - vnc-viewer
  - vscode
  - vlc
  - winscp
  - wiztree
  - winrar

# List of features: "Get-WindowsOptionalFeature -Online"
install_windows_features: false
windows_features:
  Microsoft-Hyper-V: true

# List of valid distributions that can be installed:
# wsl-alpine
# wsl-archlinux
# wsl-debiangnulinux
# wsl-fedoraremix
# wsl-kalilinux
# wsl-opensuse
# wsl-sles
# wsl-ubuntu-1604
# wsl-ubuntu-1804
# wsl-ubuntu-2004
install_wsl2: false
wsl2_distribution: wsl-ubuntu-2004

change_power_plan: false
# high_performance
# balanced
# power_saver
power_plan: "high_performance"