---

# BATTLENET
# AMD ADRENALIN
# ASETEK RACEHUB
# gamadv-xtd3

install_chocolately_packages: true
choco_installed_packages:
  - adobereader
  - aida64-extreme
  - autodesk-fusion360
  - brave
  - discord.install
  - epicgameslauncher
  - gpu-z
  - icue
  - imgburn
  - lghub
  - msiafterburner
  - orcaslicer
  - rpi-imager
  - steam
  - tailscale
  ### Default Apps
  - cpu-z
  - displaycal
  - everything
  - firefox
  - git
  - googlechrome
  - googledrive
  - hwinfo
  - lghub
  - microsoft-windows-terminal
  - obs-studio
  - revo-uninstaller
  - spotify
  - vscode
  - vlc
  - winscp
  - wiztree
  - winrar

install_chocolatey_custom_packages: true
choco_custom_installed_packages:
  - git --params /NoShellIntegration
  - microsoft-office-deployment --params"/64bit /Product:O365ProPlusRetail,VisioProRetail /Exclude:Groove,Lync,Publisher"
  - tightvnc --installArguments ADDLOCAL=Viewer

install_winget_packages: true
winget_packages:
  - name: Elgato.CameraHub
    source: winget

# List of features: "Get-WindowsOptionalFeature -Online"
install_windows_features: false
windows_features:
  Microsoft-Hyper-V: true

# List of valid distributions that can be installed:
# wsl-alpine
# wsl-archlinux
# wsl-debiangnulinux
# wsl-fedoraremix
# wsl-kalilinux
# wsl-opensuse
# wsl-sles
# wsl-ubuntu-1604
# wsl-ubuntu-1804
# wsl-ubuntu-2004
install_wsl2: false
wsl2_distribution: wsl-ubuntu-2004

change_power_plan: false
# high_performance
# balanced
# power_saver
power_plan: "high_performance"

postinstall_notes: true
postinstall_items:
  - "Manual Install: AMD Adrenalin, Asetek Racehub, Battle.NET, GAMADV-XTD3"
  - "Validate Cygwin Theme"
  - "Google Drive Folders: Gam, OrcaSlicer"
  - "Displaycal calibrations"