---
- name: Update and upgrade apt packages
  apt:
    update_cache: yes
    upgrade: dist

- name: Uninstall unncessary Packages
  apt:
    name:
      - wolfram-engine
      - scratch
      - scratch2
      - nuscratch
      - sonic-pi
      - idle3
      - smartsim
      - ava-common
      - minecraft-pi
      - libreoffice*
    state: absent
    autoclean: true
    autoremove: true

- name: Install necessary packages
  apt:
    name:
      - git
      - curl
      - build-essential
      - npm
    state: present

- name: Ensure the rainbow screen is disabled
  lineinfile:
    path: /boot/firmware/config.txt
    regexp: '^disable_splash='
    line: 'disable_splash=1'
    state: present

- name: Install x11-xserver-utils if not present
  apt:
    name: x11-xserver-utils
    state: present

- name: Ensure screensaver is disabled in LXDE
  blockinfile:
    path: /etc/xdg/lxsession/LXDE/autostart
    block: |
      @xset s off          # don't activate screensaver
      @xset -dpms          # disable DPMS (Energy Star) features
      @xset s noblank      # don't blank the video device

- name: Ensure screensaver is disabled in LXDE-pi
  blockinfile:
    path: /etc/xdg/lxsession/LXDE-pi/autostart
    block: |
      @xset s off          # don't activate screensaver
      @xset -dpms          # disable DPMS (Energy Star) features
      @xset s noblank      # don't blank the video device

- name: Ensure the low voltage warning is disabled
  lineinfile:
    path: /boot/firmware/config.txt
    regexp: '^avoid_warnings='
    line: 'avoid_warnings=1'
    state: present

- name: Remove SSH password warning flag
  file:
    path: /etc/xdg/lxsession/LXDE-pi/sshpwd.sh
    state: absent

- name: Disable Bluetooth Hardware
  lineinfile:
    dest: /boot/firmware/config.txt
    line: "dtoverlay=disable-bt"

- name: Disable Bluetooth Service
  ansible.builtin.systemd:
    name: hciuart
    enabled: no
    state: stopped