---
- name: Configure fullpageos on Raspberry Pi
  hosts: "{{ hosts }}"
  become: yes
  become_user: pi
  gather_facts: no

  tasks:
    - name: Update OS
      ansible.builtin.import_tasks:
        file: tasks/updates.yml
      tags: ["update"]   

    - name: Configure Chromium
      ansible.builtin.import_tasks:
        file: tasks/chromium.yml
      tags: ["chromium"]   

  handlers:
    - name: Restart Magic Mirror
      shell: "cd {{ mm_root }} && pm2 restart MagicMirror"
      ignore_errors: true
