---
- hosts: "{{ hosts }}"
  become: true
  become_user: "{{ becomeuser }}"
  tasks:
    - name: Install Chocolatey packages.
      chocolatey.chocolatey.win_chocolatey:
        name: "{{ item.name | default(item) }}"
        state: "{{ item.state | default('present') }}"
        version: "{{ item.version | default(omit) }}"
        choco_args: "{{ item.choco_args | default('--ignore-checksum') }}"
      loop:
        - 7zip
        - duck
        - everything
        - filezilla
        - firefox
        - git
        - googlechrome
        - googledrive
        - hwinfo
        - lghub
        - microsoft-windows-terminal
        - obs-studio
        - powertoys
        - revo-uninstaller
        - spotify
        - vscode
        - vlc
        - vmrc
        - winscp
        - wiztree
        - zoom

    - name: Clean chocolatey and nuget cache.
      block:
        - name: Clean up the chocolatey and NuGet cache.
          ansible.windows.win_file:
            path: "{{ item }}"
            state: absent
          loop:
            - '%UserProfile%\AppData\Local\Temp\chocolatey\'
            - '%UserProfile%\AppData\Local\Temp\nuget\'
            - '%UserProfile%\AppData\Local\NuGet\Cache\'
          register: cleanup_task
      rescue:
        - name: "{{ cleanup_task.msg }}"
          ansible.builtin.debug:
            msg: >
              "Some chocolatey cache files are still in use. You may need to reboot your machine to resolve the error"