---
- hosts: "{{ hosts }}"
  become: true
  become_user: "{{ becomeuser }}"
  tasks:
    - name: Remove bloatware
      ansible.windows.win_package:
        product_id: "{{ item.name | default(item) }}"
        state: absent
      loop:
        - Microsoft.BingNews
        - Microsoft.BingWeather
        - Microsoft.GamingApp
        - Microsoft.GetHelp
        - Microsoft.Getstarted
        - Microsoft.Messaging
        - Microsoft.Microsoft3DViewer
        - Microsoft.MicrosoftOfficeHub
        - Microsoft.MicrosoftSolitaireCollection
        - Microsoft.MicrosoftStickyNotes
        - Microsoft.MixedReality.Portal
        # - Microsoft.MSPaint
        - Microsoft.Office.OneNote
        - Microsoft.OneConnect
        - Microsoft.People
        - Microsoft.PowerAutomateDesktop
        - Microsoft.Print3D
        - Microsoft.ScreenSketch
        - Microsoft.SkypeApp
        - Microsoft.Todos
        - Microsoft.Windows.Photos
        - Microsoft.WindowsAlarms
        # - Microsoft.WindowsCalculator
        - Microsoft.Wallet
        - Microsoft.WindowsCamera
        # - microsoft.windowscommunicationsapps
        - Microsoft.WindowsFeedbackHub
        - Microsoft.WindowsMaps
        - Microsoft.WindowsSoundRecorder
        - Microsoft.Xbox
        - Microsoft.Xbox.TCUI
        - Microsoft.XboxApp
        - Microsoft.XboxGameOverlay
        - Microsoft.XboxSpeechToTextOverlay
        - Microsoft.YourPhone
        - Microsoft.ZuneMusic
        - Microsoft.ZuneVideo
        - MicrosoftTeams
