---
  - name: Uninstall Unncessary Packages
    become: true
    apt:
      pkg:
        - wolfram-engine
        - scratch
        - scratch2
        - nuscratch
        - sonic-pi
        - idle3
        - smartsim
        - ava-common
        - minecraft-pi
        - libreoffice*
      state: "absent"
      autoclean: true
      autoremove: true

  - name: Update Packages
    become: true
    ansible.builtin.apt:
      update_cache: yes

  - name: Upgrade the OS Distribution
    become: true
    ansible.builtin.apt:
      upgrade: dist

  - name: Upgrade the OS
    become: true
    ansible.builtin.apt:
      name: "*"
      state: latest

  - name: Install MM Packages
    become: true
    ansible.builtin.apt:
      pkg:
        - python3
        - python3-pip
        - git
        - python3-dev
        - sshpass
        - mpg321
        - alsa-utils

  - name: Disable Bluetooth Hardware
    become: true
    lineinfile:
      dest: /boot/config.txt
      line: "dtoverlay=pi3-disable-bt"

  - name: Disable Bluetooth Service
    become: true
    ansible.builtin.systemd:
      name: hciuart
      enabled: no
      state: stopped

  - name: Install NTP
    apt:
      name: ntp
      state: present

  - name: Start NTP
    service:
      name: ntpd
      state: started
      enabled: yes