---
- name: Install custom Chocolatey packages
  ansible.windows.win_powershell:
    script: |
      # Choco install command
      C:\ProgramData\chocolatey\bin\choco.exe install "{{ item }}" --fail-on-unfound --yes --no-progress --limit-output --timeout 2700 --ignore-checksum
  loop: "{{ choco_custom_installed_packages }}"

- name: Clean chocolatey and nuget cache
  block:
    - name: Clean up the chocolatey and NuGet cache.
      ansible.windows.win_file:
        path: "{{ item }}"
        state: absent
      loop:
        - '%UserProfile%\AppData\Local\Temp\chocolatey\'
        - '%UserProfile%\AppData\Local\Temp\nuget\'
        - '%UserProfile%\AppData\Local\NuGet\Cache\'
      register: cleanup_task
  rescue:
    - name: "{{ cleanup_task.msg }}"
      ansible.builtin.debug:
        msg: >
          "Some chocolatey cache files are still in use. You may need to reboot your machine to resolve the error"
