---
- name: Copy Shortcut links to Start Menu folder
  ansible.windows.win_powershell:
    script: |
      # Define the source file and destination paths
      $sourceFile = "{{ item }}"
      $destinationFolder = "$env:APPDATA\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar"

      # Get the file name from the source file path
      $fileName = Split-Path -Path $sourceFile -Leaf

      # Define the destination file path
      $destinationFile = Join-Path -Path $destinationFolder -ChildPath $fileName

      # Copy the shortcut file to the destination folder
      Copy-Item -Path $sourceFile -Destination $destinationFile
  loop: "{{ taskbar_pinned_icons }}"

- name: Copy registry file to Windows host
  win_copy:
    src: "files/{{ custom_taskbar_reg }}"
    dest: "C:\Windows\Temp\{{ custom_taskbar_reg }}"

- name: Import the registry file
  win_shell: |
    reg import "C:\Windows\Temp\{{ custom_taskbar_reg }}"