---
- name: Remove shortcuts from desktop
  ansible.windows.win_powershell:
    script: |
      # Remove .lnk files from Public Desktop
      $publicDesktop = "C:\Users\Public\Desktop"
      Get-ChildItem -Path $publicDesktop -Filter *.lnk -Recurse | Remove-Item -Force

      # Remove .lnk files from all user home directories
      $userProfiles = Get-ChildItem -Path C:\Users
      foreach ($userProfile in $userProfiles) {
          if (Test-Path "$($userProfile.FullName)\Desktop") {
              Get-ChildItem -Path "$($userProfile.FullName)\Desktop" -Filter *.lnk -Recurse | Remove-Item -Force
          }
      }

