---
# - name: Get user profile path
#   ansible.windows.win_command: powershell.exe -
#   args:
#     stdin: echo $HOME
#   register: user_home_path

# - name: Get shortcuts
#   ansible.windows.win_find:
#     paths:
#       - C:\Users\Public\Desktop
#       - '{{ user_home_path.stdout | trim }}\Desktop'
#       - '{{ user_home_path.stdout | trim }}\OneDrive\Desktop'
#     patterns: "*.lnk"
#   register: shortcuts

# - name: Remove shortcuts from the Desktop
#   ansible.windows.win_file:
#     path: "{{ item.path }}"
#     state: absent
#   loop: "{{ shortcuts.files | unique }}"
#   when: shortcuts.files | length > 0

- name: Remove shortcuts from desktop
  ansible.windows.win_powershell:
    script: |
      # Remove .lnk files from Public Desktop
      $publicDesktop = "C:\Users\Public\Desktop"
      Get-ChildItem -Path $publicDesktop -Filter *.lnk -Recurse | Remove-Item -Force

      # Remove .lnk files from all user home directories
      $userProfiles = Get-ChildItem -Path C:\Users
      foreach ($userProfile in $userProfiles) {
          if (Test-Path "$($userProfile.FullName)\Desktop") {
              Get-ChildItem -Path "$($userProfile.FullName)\Desktop" -Filter *.lnk -Recurse | Remove-Item -Force
          }
      }

