---
- name: Enable the file extension in file names, disable folder checkboxes
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    name: "{{ item }}"
    data: 0
    type: dword
  loop:
    - AutoCheckSelect
    - HideFileExt

- name: Set full path in toolbar
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\CabinetState
    name: "{{ item }}"
    data: 1
    type: dword
  loop:
    - FullPath

- name: Default Control Panel view
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\ControlPanel
    name: "{{ item }}"
    data: 1
    type: dword
  loop:
    - AllItemsIconView
    - StartupPage

- name: Default Control Panel view
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\ControlPanel
    name: "{{ item }}"
    data: 1
    type: dword
  loop:
    - AllItemsIconView
    - StartupPage

- name: Enable expanded stats for file transfers
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\OperationStatusManager
    name: "{{ item }}"
    data: 1
    type: dword
  loop:
    - EnthusiastMode

- name: Disable recently accessed file history
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer
    name: "{{ item }}"
    data: 0
    type: dword
  loop:
    - ShowCloudFilesInQuickAccess
    - ShowFrequent
    - ShowRecent

- name: Enable right-click context menu
  ansible.windows.win_regedit:
    path: HKCU:\Software\Classes\CLSID\{86ca1aa0-34aa-4e8b-a509-50c905bae2a2}\InprocServer32
    data: "-"
    type: string

- name: Disable Edge first run experience
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Edge
    name: "{{ item }}"
    data: 1
    type: dword
  loop:
    - HideFirstRunExperience

- name: Remove from startup
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Run
    name: Spotify
    state: absent
