---
- name: Enable the file extension in file names
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    name: HideFileExt
    data: 0
    type: dword

- name: Set Explorer to the Computer view, use Compact mode
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    name: "{{ item }}"
    data: 1
    type: dword
  loop:
    - LaunchTo
    - UseCompactMode

- name: Default Control Panel view
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\ControlPanel
    name: "{{ item }}"
    data: 1
    type: dword
  loop:
    - AllItemsIconView
    - StartupPage

- name: Enable expanded stats for file transfers
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\OperationStatusManager
    name: EnthusiastMode
    data: 1
    type: dword

- name: Disable recently accessed file history
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer
    name: "{{ item }}"
    data: 0
    type: dword
  loop:
    - ShowCloudFilesInQuickAccess
    - ShowFrequent
    - ShowRecent

- name: Enable right-click context menu
  ansible.windows.win_regedit:
    path: HKCU:\Software\Classes\CLSID\{86ca1aa0-34aa-4e8b-a509-50c905bae2a2}\InprocServer32
    data: "-"
    type: string

- name: Disable Edge first run experience
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Edge
    name: HideFirstRunExperience
    data: 1
    type: dword