---
# - name: Postinstall TODO
#   ansible.windows.win_powershell:
#     script: |
#       $desktopPath = [System.Environment]::GetFolderPath('Desktop')
#       $filePath = Join-Path - Path $desktopPath - ChildPath 'TODO.txt'
#       $content = @(
#       ' Pin Icons: Chrome, Explorer, Outlook, AD, Everything, GPO, Cygwin, RDP'
#       ' Install Google Workspace Sync https://tools.google.com/dlpage/gssmo/ '
#       ' Validate Cygwin Theme'
#       ' Install and configure Sophos VPN'
#       ' Outlook: Remove Favorites Bar, Use Tighter Spacing, Expand Ribbon, Conditional Formatting Blue, File Options Advanced Show Apps In outlook Off, Signature'
#       ' Power Options, Disable Fast Startup'
#       'adobe acrobat, adobe creative cloud, automox, crowdstrike, dell command update, ducky rgb, gamadv-xtd3, veeam, lsagent, rdm'
#       )

- name: Ensure the file exists on the user's desktop
  win_file:
    path: "{{ lookup('env', 'USERPROFILE') }}\\Desktop\\TODO.txt"
    state: touch

- name: Add lines of content to the file on the user's desktop
  win_lineinfile:
    path: "{{ lookup('env', 'USERPROFILE') }}\\Desktop\\TODO.txt"
    line: "{{ item }}"
  loop:
    - Line 1: This is the first line of content.
    - Line 2: This is the second line of content.
    - Line 3: This is the third line of content.

    - Line 1: "Pin Icons: Chrome, Explorer, Outlook, AD, Everything, GPO, Cygwin, RDP"
    - Line 2: "Install Google Workspace Sync https://tools.google.com/dlpage/gssmo/"
    - Line 3: "Validate Cygwin Theme"
    - Line 4: "Install and configure Sophos VPN"
    - Line 5: "Outlook: Remove Favorites Bar, Use Tighter Spacing, Expand Ribbon, Conditional Formatting Blue, File Options Advanced Show Apps In outlook Off, Signature"
    - Line 6: "Power Options, Disable Fast Startup"
    - Line 7: "Manual Install: adobe acrobat, adobe creative cloud, automox, crowdstrike, dell command update, ducky rgb, gamadv-xtd3, veeam, lsagent, rdm"