---

- name: Get current timezone
  community.windows.win_timezone:
    state: get
  register: current_timezone

- name: Set timezone to 'Eastern Standard Time' if not already set
  community.windows.win_timezone:
    timezone: Eastern Standard Time
  when: current_timezone.timezone != "Eastern Standard Time"

# - name: Set 'Eastern Standard Time' timezone
#   community.windows.win_timezone:
#     timezone: Eastern Standard Time

- name: Set Time Format
  ansible.windows.win_regedit:
    path: HKCU:\Control Panel\International
    name: sTimeFormat
    data: HH:mm:ss
    type: string

- name: Set Short Time
  ansible.windows.win_regedit:
    path: HKCU:\Control Panel\International
    name: sShortTime
    data: HH:mm
    type: string