---

- name: Get current timezone
  win_shell: |
    (Get-TimeZone).Id
  register: current_timezone

- name: Debug current timezone
  debug:
    msg: "Current timezone is {{ current_timezone.stdout }}"

- name: Set timezone to 'Eastern Standard Time' if not already set
  community.windows.win_timezone:
    timezone: Eastern Standard Time
  when: current_timezone.stdout.strip() != "Eastern Standard Time"

- name: Set Time Format
  ansible.windows.win_regedit:
    path: HKCU:\Control Panel\International
    name: sTimeFormat
    data: HH:mm:ss
    type: string

- name: Set Short Time
  ansible.windows.win_regedit:
    path: HKCU:\Control Panel\International
    name: sShortTime
    data: HH:mm
    type: string