---
- name: Install RSAT
  ansible.windows.win_powershell:
    script: |
      Add-WindowsCapability -online -Name "{{ item }}"
  loop: "{{ winget_packages }}"
  - Rsat.FileServices.Tools~~~~0.0.1.0
  - Rsat.GroupPolicy.Management.Tools~~~~0.0.1.0
  - Rsat.IPAM.Client.Tools~~~~0.0.1.0
  - Rsat.LLDP.Tools~~~~0.0.1.0
  - Rsat.NetworkController.Tools~~~~0.0.1.0
  - Rsat.NetworkLoadBalancing.Tools~~~~0.0.1.0
  - Rsat.BitLocker.Recovery.Tools~~~~0.0.1.0
  - Rsat.CertificateServices.Tools~~~~0.0.1.0
  - Rsat.DHCP.Tools~~~~0.0.1.0
  - Rsat.FailoverCluster.Management.Tools~~~~0.0.1.0
  - Rsat.RemoteAccess.Management.Tools~~~~0.0.1.0
  - Rsat.RemoteDesktop.Services.Tools~~~~0.0.1.0
  - Rsat.ServerManager.Tools~~~~0.0.1.0
  - Rsat.Shielded.VM.Tools~~~~0.0.1.0
  - Rsat.StorageMigrationService.Management.Tools~~~~0.0.1.0
  - Rsat.StorageReplica.Tools~~~~0.0.1.0
  - Rsat.SystemInsights.Management.Tools~~~~0.0.1.0
  - Rsat.VolumeActivation.Tools~~~~0.0.1.0
  - Rsat.WSUS.Tools~~~~0.0.1.0