---
- name: Create Scheduled Tasks
  win_scheduled_task:
    name: Update Chocolatey Packages
    description: Upgrade all Chocolatey packages daily at 9pm
    actions:
    - path: powershell.exe
      arguments: |
        "C:\\ProgramData\\chocolatey\\bin\\choco.exe upgrade all -y"
    triggers:
    - type: daily
      start_boundry: '2024-06-18T21:00:00'
      repetition:
        interval: PT24H
    username: SYSTEM
    run_level: highest
    state: present
    enabled: yes