---
- name: Install winget packages
  ansible.windows.win_powershell:
    script: |
      $app = "{{ item.name | default(item) }}"
      winget install --accept-package-agreements --accept-source-agreements -h -s "winget" $app
  loop: "{{ winget_packages }}"
