---
install_magicmirror: true
install_modules: true
config_replace: true

mm_root: '/home/pi/MagicMirror' # Root install directory for MagicMirrorOS.

mm_modules:
  - name: alert

  - name: updatenotification
    position: top_bar 

  - name: clock
    position: top_left

  - name: weather
    position: top_left
    config:
      weatherProvider: openweathermap
      type: current
      locationID: 5005703
      apiKey: "{{ openweather_api_key }}"

  - name: MMM-iFrame
    github: https://github.com/alberttwong/MMM-iFrame.git
    position: bottom_right
    config:
      url:
        https://www.youtube.com/embed/Nq4Ge6foW4Y?autoplay=1
      updateInterval: 86400000
      width: 1920
      height: 1275
      frameWidth: 510

  - name: MMM-iFrame
    github: https://github.com/alberttwong/MMM-iFrame.git
    position: bottom_left
    config:
      url:
        https://api.wetmet.net/client-content/PlayerFrame.php?CAMERA=210-02-01&amp;CFVER=WM&amp;WIDTH=640&amp;HEIGHT=360
      updateInterval: 86400000
      width: 1920
      height: 1275
      frameWidth: 510

  - name: MMM-RAIN-MAP
    github: https://github.com/jalibu/MMM-RAIN-MAP.git
    position: top_right
    config:
      animationSpeedMs: 1000
      colorScheme: 8
      colorizeTime: true
      defaultZoomLevel: 8
      displayTime: true
      displayTimeline: true
      displayClockSymbol: true
      displayHoursBeforeRain: -1
      extraDelayLastFrameMs: 1000
      extraDelayCurrentFrameMs: 10000
      invertColors: false
      markers:
        lat: 42.479840
        lng: -83.893636
        color: red
      mapPositions:
        lat: 42.479840
        lng: -83.893636
        zoom: 6
        loops: 5
      mapUrl: https://a.tile.openstreetmap.de/{z}/{x}/{y}.png
      mapHeight: 250px
      mapWidth: 350px
      maxHistoryFrames: 7
      maxForecastFrames: 0
      substitudeModules:
      timeFormat: 24
      updateIntervalInSeconds: 300

  # - name: MMM-RTSPStream
  #   github: https://github.com/shbatm/MMM-RTSPStream.git
  #   position: middle_center
  #   config:
  #     initialSetup: true