---
- name: Install MagicMirror on Raspberry Pi
  hosts: "{{ hosts }}"
  become: yes
  become_user: pi
  gather_facts: no
  vars_files:
    - "{{ playbook_dir }}/files/{{hosts}}.yml"

  tasks:
    - name: Install MagicMirror
      ansible.builtin.import_tasks:
        file: tasks/install_mm.yml
      when: install_magicmirror
      tags: ["magicmirror"]   

    - name: Install MagicMirror Modules
      ansible.builtin.import_tasks:
        file: tasks/install_modules.yml
      when: install_modules
      tags: ["modules"]   

    - name: Upgrade MagicMirror
      ansible.builtin.import_tasks:
        file: tasks/upgrade_mm.yml
      when: upgrade_mm
      tags: ["upgrade"]   

    - name: Generate MagicMirror Configuration
      ansible.builtin.import_tasks:
        file: tasks/config_replace.yml
      when: config_replace
      tags: ["configure"]      

  handlers:
    - name: Restart Magic Mirror
      shell: "cd {{ mm_root }} && pm2 restart MagicMirror"
      ignore_errors: true

    # - name: Install Modules
    #   ansible.builtin.import_tasks:
    #     file: tasks/install_modules.yml
    #   when: install_modules
    #   tags: ["modules"]   

    # - name: Start MM2
    #   ansible.builtin.import_tasks:
    #     file: tasks/start_mm.yml
    #   when: start_mm
    #   tags: ["start_mm"]   
# We're ready! Run pm2 start MagicMirror from the ~/MagicMirror directory to start your MagicMirror.