---
configure_explorer: false
configure_hostname: false
configure_start_menu: false
configure_taskbar: false
disable_mouse_acceleration: false
remote_desktop_enabled: false
remove_desktop_icons: false
set_sound_scheme: false

install_windows_updates: false
windows_updates_reboot: false
update_categories:
  # You can install only specific updates by uncommenting it
  # * - installs all updates
  # - "*"
  - Critical Updates
  # - Definition Updates
  # - Developer Kits
  # - Feature Packs
  - Security Updates
  # - Service Packs
  # - Tools
  - Update Rollups
  # - Updates
  # - Upgrades

change_power_plan: false
# high_performance
# balanced
# power_saver
power_plan: "high_performance"

install_chocolatey_packages: true
choco_installed_packages:
  - cpu-z    
  - everything
  - firefox
  - git
  - googlechrome
  - googledrive
  - hwinfo
  - lghub
  - microsoft-windows-terminal
  - obs-studio
  - revo-uninstaller
  - spotify
  - tightvnc
  - vscode
  - vlc
  - winscp
  - wiztree
  - winrar

install_winget_packages: false
winget_packages:
  # - name: "Auto Dark Mode"
  #   source: winget
  - name: WinDynamicDesktop
    source: winget

install_fonts: false
installed_nerdfonts:
  - FiraCode
  - FantasqueSansMono

install_ohmyposh: true

# List of features: "Get-WindowsOptionalFeature -Online"
install_windows_features: false
windows_features:
  Microsoft-Hyper-V: true

# List of valid distributions that can be installed:
# wsl-alpine
# wsl-archlinux
# wsl-debiangnulinux
# wsl-fedoraremix
# wsl-kalilinux
# wsl-opensuse
# wsl-sles
# wsl-ubuntu-1604
# wsl-ubuntu-1804
# wsl-ubuntu-2004
install_wsl2: false
wsl2_distribution: wsl-ubuntu-2004

remove_bloatware: false
bloatware:
  - Microsoft.BingNews
  - Microsoft.BingWeather
  - Microsoft.GamingApp
  - Microsoft.GetHelp
  - Microsoft.Getstarted
  # - Microsoft.Messaging
  - Microsoft.Microsoft3DViewer
  - Microsoft.MicrosoftOfficeHub
  - Microsoft.MicrosoftSolitaireCollection
  - Microsoft.MicrosoftStickyNotes
  - Microsoft.MixedReality.Portal
  # - Microsoft.MSPaint
  - Microsoft.Office.OneNote
  - Microsoft.OneConnect
  - Microsoft.People
  - Microsoft.PowerAutomateDesktop
  - Microsoft.Print3D
  - Microsoft.ScreenSketch
  - Microsoft.SkypeApp
  - Microsoft.Todos
  - Microsoft.Windows.Photos
  - Microsoft.WindowsAlarms
  # - Microsoft.WindowsCalculator
  - Microsoft.Wallet
  - Microsoft.WindowsCamera
  # - microsoft.windowscommunicationsapps
  - Microsoft.WindowsFeedbackHub
  - Microsoft.WindowsMaps
  - Microsoft.WindowsSoundRecorder
  - Microsoft.Xbox
  - Microsoft.Xbox.TCUI
  - Microsoft.XboxApp
  - Microsoft.XboxGameOverlay
  - Microsoft.XboxSpeechToTextOverlay
  # - Microsoft.YourPhone
  - Microsoft.ZuneMusic
  - Microsoft.ZuneVideo
  - MicrosoftTeams

configure_storage_sense: false
storage_sense:
  enabled: true
  run_frequency: 1
  delete_unused_files: true
  delete_recycle_bin_files: true
  recycle_bin_age: 14
  delete_downloads_files: true
  downloads_age: 14

defrag_volumes: false
include_volumes:
  - C
