---
# Ensure Docker group and user exist
- name: Ensure docker group exists
  ansible.builtin.group:
    name: docker
    state: present
  tags:
    - docker

- name: Create docker user
  ansible.builtin.user:
    name: docker
    group: docker
    home: /home/docker
    shell: /bin/bash
    state: present
  tags:
    - docker

# Add users to the Docker group
- name: Add ansible user to docker group
  ansible.builtin.user:
    name: ansible
    groups: docker
    append: yes
  tags:
    - docker

- name: Add bkrathwohl user to docker group
  ansible.builtin.user:
    name: bkrathwohl
    groups: docker
    append: yes
  tags:
    - docker

# Install Docker on Ubuntu
- name: Install prerequisites for Docker
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present
    update_cache: yes
  tags:
    - docker

- name: Add Docker's official GPG key
  ansible.builtin.shell:
    cmd: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  args:
    creates: /usr/share/keyrings/docker-archive-keyring.gpg
  tags:
    - docker

- name: Add Docker APT repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
  tags:
    - docker

- name: Install Docker
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
  tags:
    - docker

# Ensure /srv/docker directory is properly configured
- name: Ensure ACL tools are installed
  ansible.builtin.package:
    name: acl
    state: present
  tags:
    - docker

- name: Ensure /srv/docker directory exists
  ansible.builtin.file:
    path: /srv/docker
    state: directory
    owner: docker
    group: docker
    mode: '2775'
  tags:
    - docker

- name: Ensure Docker system directory exists
  ansible.builtin.file:
    path: /srv/docker/system
    state: directory
    owner: docker
    group: docker
    mode: '2775'
  tags:
    - docker

- name: Set default ACLs for /srv/docker
  ansible.builtin.command:
    cmd: setfacl -R -dm u::rwx,g::rwx,o::rx /srv/docker
  tags:
    - docker

# Configure Docker daemon to use /srv/docker/system as data-root
- name: Configure Docker daemon
  ansible.builtin.copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "data-root": "/srv/docker/system"
      }
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart Docker
  tags:
    - docker

- name: Ensure Docker tmp directory exists
  ansible.builtin.file:
    path: /srv/docker/system/tmp
    state: directory
    owner: docker
    group: docker
    mode: '1777'  # World-writable with sticky bit
  tags:
    - docker

- name: Ensure Docker service is started and enabled
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes
  tags:
    - docker

- name: Ensure Docker network "vm-network" exists
  community.docker.docker_network:
    name: vm-network
    state: present
  tags:
    - docker
