---
# Pull the dockge image
- name: Pull the dockge image from Docker Hub
  ansible.builtin.docker_image:
    name: louislam/dockge:latest
    source: pull
  tags:
    - dockge

- name: Create a directory for dockge container data
  ansible.builtin.file:
    path: /srv/docker/dockge
    state: directory
    owner: docker
    group: docker
    mode: '0755'
  tags:
    - dockge

- name: Run the dockge container
  ansible.builtin.docker_container:
    name: dockge
    image: louislam/dockge:latest
    state: started
    restart_policy: always
    volumes:
      - /srv/docker/dockge:/data
    ports:
      - "5001:80"  # Replace 8080 with the desired host port
    log_driver: "json-file"
    log_options:
      max-size: "10m"
      max-file: "3"
    detach: yes
  tags:
    - dockge

