---
configure_hostname: false
custom_hostname: bkrathwohl-pc

install_windows_updates: false
windows_updates_reboot: false
update_categories:
  # You can install only specific updates by uncommenting it
  # * - installs all updates
  # - "*"
  - Critical Updates
  # - Definition Updates
  # - Developer Kits
  # - Feature Packs
  - Security Updates
  # - Service Packs
  # - Tools
  - Update Rollups
  # - Updates
  # - Upgrades

install_chocolately_packages: true
choco_installed_packages:
  - duck
  - filezilla
  - powertoys    
  - vmrc
  - zoom
  - cpu-z
  - everything
  - firefox
  - git
  - googlechrome
  - googledrive
  - hwinfo
  - lghub
  - microsoft-windows-terminal
  - obs-studio
  - revo-uninstaller
  - spotify
  - tightvnc
  - vscode
  - vlc
  - winscp
  - wiztree
  - winrar


configure_explorer: false
configure_taskbar: false
configure_start_menu: false
change_power_plan: false
remote_desktop_enabled: false
remove_desktop_icons: false
configure_storage_sense: false
storage_sense:
  enabled: true
  run_frequency: 1
  delete_unused_files: true
  delete_recycle_bin_files: true
  recycle_bin_age: 14
  delete_downloads_files: true
  downloads_age: 14

defrag_volumes: false
include_volumes:
  - C

