---
ansible_host: bkrathwohl-pc
ansible_ssh_user: bkrathwohl


configure_hostname: false
custom_hostname: bkrathwohl-pc
install_windows_updates: false

remove_bloatware: true
bloatware:
  - Microsoft.BingNews
  - Microsoft.BingWeather
  - Microsoft.GamingApp
  - Microsoft.GetHelp
  - Microsoft.Getstarted
  # - Microsoft.Messaging
  - Microsoft.Microsoft3DViewer
  - Microsoft.MicrosoftOfficeHub
  - Microsoft.MicrosoftSolitaireCollection
  - Microsoft.MicrosoftStickyNotes
  - Microsoft.MixedReality.Portal
  # - Microsoft.MSPaint
  - Microsoft.Office.OneNote
  - Microsoft.OneConnect
  - Microsoft.People
  - Microsoft.PowerAutomateDesktop
  - Microsoft.Print3D
  - Microsoft.ScreenSketch
  - Microsoft.SkypeApp
  - Microsoft.Todos
  - Microsoft.Windows.Photos
  - Microsoft.WindowsAlarms
  # - Microsoft.WindowsCalculator
  - Microsoft.Wallet
  - Microsoft.WindowsCamera
  # - microsoft.windowscommunicationsapps
  - Microsoft.WindowsFeedbackHub
  - Microsoft.WindowsMaps
  - Microsoft.WindowsSoundRecorder
  - Microsoft.Xbox
  - Microsoft.Xbox.TCUI
  - Microsoft.XboxApp
  - Microsoft.XboxGameOverlay
  - Microsoft.XboxSpeechToTextOverlay
  # - Microsoft.YourPhone
  - Microsoft.ZuneMusic
  - Microsoft.ZuneVideo
  - MicrosoftTeams

install_winget_packages: false
install_windows_features: false
install_wsl2: false
install_fonts: false
install_ohmyposh: false
configure_explorer: false
configure_taskbar: false
configure_start_menu: false
set_sound_scheme: false
disable_mouse_acceleration: false
change_power_plan: false
remote_desktop_enabled: false
remove_desktop_icons: false
configure_storage_sense: false
defrag_volumes: false

install_chocolately_packages: true
choco_installed_packages:
  - duck
  - filezilla
  - powertoys    
  - vmrc
  - zoom
  - cpu-z
  - everything
  - firefox
  - git
  - googlechrome
  - googledrive
  - hwinfo
  - lghub
  - microsoft-windows-terminal
  - obs-studio
  - revo-uninstaller
  - spotify
  - tightvnc
  - vscode
  - vlc
  - winscp
  - wiztree
  - winrar
  - putty
