---
ansible_host: bkrathwohl-pc
ansible_ssh_user: bkrathwohl

install_chocolatey_packages: true
choco_installed_packages:
  name:
  - cpu-z
  - duck
  - everything
  - filezilla
  - firefox
  - git
  - googlechrome
  - googledrive
  - hwinfo
  - lghub
  - microsoft-windows-terminal
  - obs-studio
  - powertoys    
  - revo-uninstaller
  - spotify
  - tightvnc
  - vlc
  - vmrc
  - vscode
  - winscp
  - wiztree
  - winrar
  - zoom
configure_taskbar: true

# ELGATO CAMERA HUB