---
ansible_ssh_user: bkrathwohl

install_chocolatey_packages: true
choco_installed_packages:
  - cpu-z
  - everything
  - firefox
  - git
  - googlechrome
  - googledrive
  - hwinfo
  - lghub
  - microsoft-windows-terminal
  - obs-studio
  - revo-uninstaller
  - spotify
  - tightvnc
  - vscode
  - vlc
  - winscp
  - wiztree
  - winrar