---
# Install Apps via Chocolatey
- name: Ensure Chocolatey apps are installed
  win_chocolatey:
    name: 
    - 7zip
    - duck
    - everything
    - filezilla
    - git
    - googlechrome
    - googledrive
    - hwinfo
    - lghub
    - firefox
    - obs-studio
    - rdm
    - revo-uninstaller
    - spotify
    - vscode
    - vlc
    - vmrc
    - winscp
    - wiztree
    - zoom
    state: present


# Set Timezone to 'Eastern Standard Time' (GMT-05:00)
- name: Set 'Eastern Standard Time' timezone
  community.windows.win_timezone:
    timezone: Eastern Standard Time

# Left Align Start Menu
- name: Left align taskbar
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    name: TaskbarAl
    data: 0
    type: dword

# Unpin 'Search' from Taskbar
- name: Unpin 'Search' from taskbar
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Search
    name: SearchboxTaskbarMode
    data: 0
    type: dword

# Unpin Task View, Chat and Cortana from taskbar
- name: Unpin Task View, Chat and Cortana from taskbar
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    name: "{{ item }}"
    data: 0
    type: dword
  loop:
    - ShowCortanaButton
    - ShowTaskViewButton
    - TaskbarDa
    - TaskbarMn
# Unpin 'News and Interests' from taskbar
- name: Unpin 'News and Interests' from taskbar
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\Windows Feeds
    name: EnableFeeds
    data: 0
    type: dword
    state: present

# Unpin 'People' from taskbar  
- name: Unpin 'People' from taskbar
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced\People
    name: PeopleBand
    data: 0
    type: dword

# Unpin 'Edge', 'Store' other built-in shortcuts from taskbar
- name: Unpin 'Edge', 'Store' other built-in shortcuts from taskbar
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Taskband
    name: Favorites
    state: absent

- name: Disable Automatic Install of Suggested Apps.
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager
    name: SilentInstalledAppsEnabled
    data: 0
    type: dword

- name: Disable App Suggestions in Start menu.
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager
    name: SystemPaneSuggestionsEnabled
    data: 0
    type: dword

- name: Disable popup "tips" about Windows.
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager
    name: SoftLandingEnabled
    data: 0
    type: dword

- name: Disable 'Windows Welcome Experience'.
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager
    name: "{{ item }}"
    data: 0
    type: dword
  loop:
    - SubscribedContent-310093Enabled
    - SubscribedContent-338388Enabled
    - SubscribedContent-338389Enabled
    - SubscribedContent-88000326Enabled


https://github.com/AlexNabokikh/windows-playbook/blob/master/tasks/taskbar.yml

chocolatey update task
- name: Upgrade installed packages
  win_chocolatey:
    name: all
    state: latest

w11 debloat
delete all desktop icons
default browser
windows 11 expanded context menu

adobe acrobat
adobe creative cloud
automox
crowdstrike
dell command update
ducky rgb
elgato camera hub
gamadv-xtd3
veeam
lsagent
microsoft 365 apps for enterprise
microsoft visio
screenconnect
splashtop for rmm
google-workspace-sync
realvnc
sophosconnect