---
- hosts: "{{ hosts }}"
  become: true
  become_user: "{{ becomeuser }}"
  vars_files: 
    - "./bkrathwohl-pc.yml"
  gather_facts: no

  tasks:
    - name: Print variables for debugging
      ansible.builtin.debug:
        msg: 
          - "hosts: {{ hosts }}"
          - "become_user: {{ becomeuser }}"
          - "hostvar: {{ hostvar }}"
          - "choco_additional_packages: {{ choco_additional_packages }}"

 ##################
 ### Chocolatey ###
 ##################
    - name: Install Chocolatey packages
      chocolatey.chocolatey.win_chocolatey:
        name: "{{ item.name | default(item) }}"
        state: "{{ item.state | default('present') }}"
        version: "{{ item.version | default(omit) }}"
        choco_args: "{{ item.choco_args | default(--ignore-checksum) }}"
      loop: "{{ choco_additional_packages }}"

    - name: Clean chocolatey and nuget cache
      block:
        - name: Clean up the chocolatey and NuGet cache
          ansible.windows.win_file:
            path: "{{ item }}"
            state: absent
          loop:
            - '%UserProfile%\AppData\Local\Temp\chocolatey\'
            - '%UserProfile%\AppData\Local\Temp\nuget\'
            - '%UserProfile%\AppData\Local\NuGet\Cache\'
          register: cleanup_task
      rescue:
        - name: "{{ cleanup_task.msg }}"
          ansible.builtin.debug:
            msg: >
              "Some chocolatey cache files are still in use. You may need to reboot your machine to resolve the error."

 ##################
 #### Taskbar ####
 ##################
    - name: Unpin 'Search' from Taskbar
      ansible.windows.win_regedit:
        path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Search
        name: SearchboxTaskbarMode
        data: 0
        type: dword

    - name: Unpin Task View, Chat, Cortana, and left-align taskbar
      ansible.windows.win_regedit:
        path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
        name: "{{ item }}"
        data: 0
        type: dword
      loop:
        - ShowCortanaButton
        - ShowTaskViewButton
        - TaskbarDa
        - TaskbarMn
        - TaskbarAl

    - name: Unpin 'News and Interests' from Taskbar
      ansible.windows.win_regedit:
        path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\Windows Feeds
        name: EnableFeeds
        data: 0
        type: dword
        state: present

    - name: Unpin 'People' from Taskbar
      ansible.windows.win_regedit:
        path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced\People
        name: PeopleBand
        data: 0
        type: dword

    - name: Unpin 'Edge', 'Store' other built-in shortcuts from Taskbar
      ansible.windows.win_regedit:
        path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Taskband
        name: Favorites
        state: absent